# Book settings
title: Programming Differential Privacy
author: Joseph P. Near and Chiké Abuah
copyright: "2023"
logo: logo.png

execute:
  timeout: -1
  execute_notebooks: force

sphinx:
  config:
    language: en
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

html:
  favicon                   : favicon.png
  use_edit_page_button      : true
  use_repository_button     : true
  use_issues_button         : true

latex:
  latex_documents:
    targetname: book.tex

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath

bibtex_bibfiles:
    - references.bib

repository:
  url: https://github.com/uvm-plaid/programming-dp
  path_to_book: notebooks
  branch: master
